[package]
name = "atcoder-with-creusot"
version = "0.1.0"
edition = "2024"

[dependencies]
creusot-contracts = "0.4.0"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(creusot)'] }
